embedding_model: "microsoft/codebert-base"
clustering_method: "hdbscan"

clustering_params:
  min_cluster_size: 5

visualization:
  n_neighbors: 15
  min_dist: 0.1

data:
  input_path: "data/student_solutions/"
