embedding_model: "microsoft/codebert-base"
clustering_method: "hdbscan"

clustering_params:
  min_cluster_size: 5

visualization:
  n_neighbors: 15
  min_dist: 0.1

data:
  input_path: "C:/Users/grego/Desktop/Loesungen"
  output_path: "C:/Users/grego/Documents/GitHub/BA-VSC-Python/output"
